apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-busybox-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
