apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
      - name: prometheus
        enabled: true
  placement:
    mon:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - <NODE_NAME_1>
                    - <NODE_NAME_2>
                    - <NODE_NAME_3>
  dashboard:
    enabled: true
    ssl: false
  monitoring:
    enabled: true
  crashCollector:
    disable: false
  storage:
    useAllNodes: false
    useAllDevices: true
    config:
      osdsPerDevice: "1"
    nodes:
      - name: <NODE_NAME_1>
        devices:
          - name: nvme1n1
      - name: <NODE_NAME_2>
        devices:
          - name: nvme1n1
      - name: <NODE_NAME_3>
        devices:
          - name: nvme1n1
