apiVersion: v1
kind: Pod
metadata:
  name: fio-test
  namespace: fio
spec:
  restartPolicy: Never
  containers:
    - name: fio
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - apk add --no-cache fio && while true; do sleep 3600; done
      volumeMounts:
        - mountPath: /data
          name: fio-volume
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "250m"
          memory: "256Mi"
  volumes:
    - name: fio-volume
      persistentVolumeClaim:
        claimName: fio-pvc
