apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pvc
  namespace: fio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
