apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "test-nginx.fullname" . }}-pvc
  labels:
    app.kubernetes.io/name: {{ include "test-nginx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
